owner: kupecloud
repo: status

sites:
  # - name: Console
  #   url: https://console.kupe.cloud
  # - name: Auth
  #   url: https://auth.kupe.cloud
  # - name: Grafana
  #   url: https://grafana.kupe.cloud
  - name: Website
    url: https://kupe.cloud

status-website:
  cname: status.kupe.cloud
  logoUrl: https://kupe.cloud/logo.svg
  favicon: https://kupe.cloud/favicon.ico
  name: Kupe Status
  theme: dark
  themeUrl: https://status.kupe.cloud/kupe-theme.css
  introTitle: "**Kupe Status** — real-time monitoring of Kupe services."
  introMessage: This page shows the current status of Kupe's public services. If you're experiencing issues, check here for updates. Incidents are tracked via [GitHub Issues](https://github.com/kupecloud/status/issues).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  css: |
    .status,
    .tag,
    .badge {
      border-radius: 999px;
    }

# See https://upptime.js.org/docs/configuration for more options
