name: Pre-Commit

on:
  pull_request:
    branches:
      - main
    paths:
      - ".pre-commit-config.yaml"
      - ".upptimerc.yml"
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
      - "README.md"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-commit:
    uses: kupecloud/github-workflows/.github/workflows/pre-commit.yaml@75f2bc349709d9fec6630dbd937301d1a32708e0 # v1.1.0
